plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\cmart\\Desktop\\CLAUDE CODE\\VEDAFACIL\\aplicador-app"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]